### ISSUE TITLE
Multiple connections?

### ISSUE THREAD

**Issue by shimikano** [atareao/wireguard-indicator#1]
Thank you very much for this extension!

Since I have more than one Wireguard interface, would it be possible to add support for multiple interfaces/services with a toggle and display name per interface?

![mockup-wireguard-indicator](https://user-images.githubusercontent.com/3526886/96785684-740c3280-13ef-11eb-8fd3-7203f0df19eb.png)

The icon could then be "on" if at least one interface is up.

**Comment by mmartinortiz** [comment]
That would be indeed a very useful feature

**Comment by landsman** [comment]
I'm looking for this, too

**Comment by atareao** [comment]
![image](https://user-images.githubusercontent.com/298055/115122770-f8fc9100-9fb9-11eb-81d3-b5d012889de3.png)

Done!!!
