### ISSUE TITLE
Gtk.IconTheme.get_default() is null after a reboot

### ISSUE THREAD

**Issue by risbac** [atareao/wireguard-indicator#14]
Your extension works just fine, but I think that after every reboot, I get this error message and it's not displaying anymore. 

Ubuntu 21.04, pretty out of the box I think.

**Comment by atareao** [comment]
Fixed for GNOME 40 on tag https://github.com/atareao/wireguard-indicator/releases/tag/v6

**Comment by osieltorres** [comment]
> Fixed for GNOME 40 on tag https://github.com/atareao/wireguard-indicator/releases/tag/v6

Is this fixed for GNOME 3.38.x as well? as I am seeing same issue on Pop!_OS 21.04 with Wayland. The curious thing is that on X11 works fine.

**Comment by mel-geo** [comment]
If possible, I would appreciate a fix for 3.38.5 / Wayland also... :(    testing with PureOS
