### ISSUE TITLE
:question: How to connect without sudo password... ?

### ISSUE THREAD

**Issue by abacao** [atareao/wireguard-indicator#15]
Hello,

First of all, thanks for the extension.

I'm able to run the following command without entering a password
`sudo wg-quick up wg0`

because I have entered in the sudoers file the following
```
username ALL=NOPASSWD: /usr/bin/wg, /usr/bin/wg-quick
```

How can I enable/disable the tunnel in the extension without having to enter a password to obtain the same results than before?

**Comment by atareao** [comment]
Fixed for GNOME 40 on tag https://github.com/atareao/wireguard-indicator/releases/tag/v6 but with systemctl

**Comment by abacao** [comment]
If it is fixed, this issue can be closed
