### ISSUE TITLE
Gnome-shell 41 support

### ISSUE THREAD

**Issue by conqp** [atareao/wireguard-indicator#23]
I am running Arch Linux with `gnome-shell 1:41.4-1`. I cannot install the [plugin](https://extensions.gnome.org/extension/3612/wireguard-indicator/) due to incompatibility with my shell version. Is there any plan to support up-to-date gnome-shell versions?

**Comment by backl1n** [comment]
i have identical problem can you try repair pls

**Comment by conqp** [comment]
What worked for me is to temporarily disable the gnome shell extension version validation (dconf key `/org/gnome/shell/disable-extension-version-validation`). However, this is only a workaround.

**Comment by backl1n** [comment]
can you explain procedure ?

**Comment by conqp** [comment]
```
$ dconf write /org/gnome/shell/disable-extension-version-validation true
```

**Comment by backl1n** [comment]
ok but its disable update for all extension ?

**Comment by backl1n** [comment]
i do reinstall extension ? after disable extension update for activate this  @conqp

**Comment by zilexa** [comment]
Since Gnome 42 is around the corner.. just wondering what the plan is for Wireguard-ui?

**Comment by atareao** [comment]
Updated to 41
