### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by azcn2503** [atareao/wireguard-indicator#24]
Hey guys,

I have a couple of working wireguard configurations that I am able to start up using `sudo wg-quick up config-a.conf` and `sudo wg-quick up config-b.conf`, this works fine. I want to link up this extension so that I can see the status of those. I am not sure how I can achieve this using the fields available in the UI.

Does the extension rely on me having created services for my wireguard connections? Or does the extension manage setting that up? What should the value of the service field be when adding a new service through the wireguard preferences tab?

All I have at the moment are working .conf files, no services. Have I missed a step?

Many thanks in advance and apologies for my misunderstanding!

**Comment by jeames00** [comment]
This stumped me for a while too. Run the following command to create a systemd service from a wg-quick conf file named "config-a.conf":

`systemctl enable wg-quick@config-a`

You can then add the service name "wg-quick<span></span>@config-a.service" in the indicator's settings.

**Comment by ipeacocks** [comment]
Would like to add that if you add in sudoers:
```
your_username ALL=(ALL) NOPASSWD: /bin/systemctl start wg-quick@wg0, /bin/systemctl stop wg-quick@wg0
```
Then `wg-quick@wg0` needs to be added to extension and not `wg-quick@wg0.service`. Or vise versa.
