### ISSUE TITLE
how to remove wireguard

### ISSUE THREAD

**Issue by hosamalzagh** [atareao/wireguard-indicator#37]
my os is ubuntu 20

i try remove wireguard

sudo apt remove wireguard
sudo apt autoclean && sudo apt autoremove
Package 'wireguard' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
$ locate wireguard

/snap/core18/2667/usr/lib/python3/dist-packages/cloudinit/config/__pycache__/cc_wireguard.cpython-36.pyc
/snap/core18/2667/usr/lib/python3/dist-packages/cloudinit/config/cc_wireguard.py
/snap/core20/1778/usr/lib/python3/dist-packages/cloudinit/config/__pycache__/cc_wireguard.cpython-38.pyc
/snap/core20/1778/usr/lib/python3/dist-packages/cloudinit/config/cc_wireguard.py
/snap/core22/484/usr/lib/python3/dist-packages/cloudinit/config/__pycache__/cc_wireguard.cpython-310.pyc
/snap/core22/484/usr/lib/python3/dist-packages/cloudinit/config/cc_wireguard.py
/usr/lib/modules/5.15.0-57-generic/kernel/drivers/net/wireguard
/usr/lib/modules/5.15.0-57-generic/kernel/drivers/net/wireguard/wireguard.ko
/usr/lib/modules/5.15.0-58-generic/kernel/drivers/net/wireguard
/usr/lib/modules/5.15.0-58-generic/kernel/drivers/net/wireguard/wireguard.ko
/usr/share/doc/netplan/examples/wireguard.yaml
/usr/src/linux-hwe-5.15-headers-5.15.0-57/drivers/net/wireguard
/usr/src/linux-hwe-5.15-headers-5.15.0-57/drivers/net/wireguard/Makefile
/usr/src/linux-hwe-5.15-headers-5.15.0-57/include/uapi/linux/wireguard.h
/usr/src/linux-hwe-5.15-headers-5.15.0-57/tools/testing/selftests/wireguard
/usr/src/linux-hwe-5.15-headers-5.15.0-57/tools/testing/selftests/wireguard/netns.sh
/usr/src/linux-hwe-5.15-headers-5.15.0-57/tools/testing/selftests/wireguard/qemu
/usr/src/linux-hwe-5.15-headers-5.15.0-57/tools/testing/selftests/wireguard/qemu/Makefile
/usr/src/linux-hwe-5.15-headers-5.15.0-58/drivers/net/wireguard
/usr/src/linux-hwe-5.15-headers-5.15.0-58/drivers/net/wireguard/Makefile
/usr/src/linux-hwe-5.15-headers-5.15.0-58/include/uapi/linux/wireguard.h
/usr/src/linux-hwe-5.15-headers-5.15.0-58/tools/testing/selftests/wireguard
/usr/src/linux-hwe-5.15-headers-5.15.0-58/tools/testing/selftests/wireguard/netns.sh
/usr/src/linux-hwe-5.15-headers-5.15.0-58/tools/testing/selftests/wireguard/qemu
/usr/src/linux-hwe-5.15-headers-5.15.0-58/tools/testing/selftests/wireguard/qemu/Makefile
/var/lib/dpkg/info/wireguard-tools.list
/var/lib/dpkg/info/wireguard-tools.postrm
i try delete file

$ rm -rf cloudinit

rm: cannot remove 'cloudinit/__init__.py': Read-only file system
rm: cannot remove 'cloudinit/__pycache__/__init__.cpython-36.pyc': Read-only file sy

**Comment by atareao** [comment]
this is not a issue from this extension
