### ISSUE TITLE
Connect on startup

### ISSUE THREAD

**Issue by vincentkoevoets** [atareao/wireguard-indicator#42]
Hello, 
I am searching for a way to **not** let the plugin connect to the VPN on login. I don't always need the VPN to be connected, in fact, I only want it to connect when I tell it to. 
I use the nmcli method, can you help me with this?
Thanks for the great plugin!

**Comment by CodexHere** [comment]
@vincentkoevoets There's a couple ways about fixing this:

1) Command line:

* Ensure the connection name: `nmcli connection show`
* Modify to disable autoconnect: `nmcli connection modify "Connection Name" autoconnect off`

2) Advanced Network Options

* Either open the app "Advanced Network Options" or launch from cli: `nm-connection-editor`
* Edit configuration for your Wireguard connection
* Click `General` tab
* Uncheck "Connect automatically with priority"

There ya go!

**Comment by vincentkoevoets** [comment]
Wow, I never took the time to properly thank you, so: Thank you for the help! Works perfectly.
